### ISSUE TITLE
Typo in application configuration results in hang

### ISSUE THREAD

**Issue by fhunleth** [mobileoverlord/bootloader#4]
If you accidentally do this in your `config.exs`:
```
config :bootloader,
  init: [:nerves_init_zero],
  app: :whoops_i_typoed_my_app_name
```
The board is unresponsive. If you're able to get to the terminal, you would see this:
```
=ERROR REPORT==== 1-Jan-1970::00:00:04 ===
** Generic server 'Elixir.Bootloader.ApplicationController' terminating 
** Last message in was app
** When Server state == #{app => nerves_cam,applications => [],
                          handler => 'Elixir.Bootloader.Handler',
                          handler_state => nil,hash => nil,
                          init => [nerves_init_zero],
                          overlay_path => nil}
** Reason for termination == 
** {function_clause,
       [{'Elixir.Keyword',get,
            [nil,applications,[]],
            [{file,"lib/keyword.ex"},{line,150}]},
        {'Elixir.Bootloader.Application',applications,1,
            [{file,"lib/bootloader/application.ex"},{line,39}]},
        {'Elixir.Bootloader.Application',load,1,
            [{file,"lib/bootloader/application.ex"},{line,13}]},
        {'Elixir.Enum','-map/2-lists^map/1-0-',2,
            [{file,"lib/enum.ex"},{line,1229}]},
        {'Elixir.Bootloader.ApplicationController',build_hash,1,
            [{file,"lib/bootloader/application_controller.ex"},{line,89}]},
        {'Elixir.Bootloader.ApplicationController',build_cache,1,
            [{file,"lib/bootloader/application_controller.ex"},{line,81}]},
        {'Elixir.Bootloader.ApplicationController',handle_info,2,
            [{file,"lib/bootloader/application_controller.ex"},{line,76}]},
        {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]}]}
Interactive Elixir (1.4.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
00:00:05.084 [error] GenServer Bootloader.ApplicationController terminating
** (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:150: Keyword.get(nil, :applications, [])
    (bootloader) lib/bootloader/application.ex:39: Bootloader.Application.applications/1
    (bootloader) lib/bootloader/application.ex:13: Bootloader.Application.load/1 
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (bootloader) lib/bootloader/application_controller.ex:89: Bootloader.ApplicationController.build_hash/1
    (bootloader) lib/bootloader/application_controller.ex:81: Bootloader.ApplicationController.build_cache/1
    (bootloader) lib/bootloader/application_controller.ex:76: Bootloader.ApplicationController.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
Last message: :app
State: %{app: :nerves_cam, applications: [], handler: Bootloader.Handler, handler_state: nil, hash: nil, init: [:nerves_init_zero], overlay_path: nil}
{"Kernel pid terminated",application_controller,"{application_terminated,bootloader,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,bootloader,shutdown})

Crash dump is being written to: /root/crash.dump...erlinit: Erlang VM exited
erlinit: Sending SIGTERM to all processes
erlinit: Sending SIGKILL to all processes
erlinit: Not rebooting on exit as requested by the erlinit configuration...
[   12.745130] musb-hdrc musb-hdrc.1.auto: remove, state 4
[   12.750439] usb usb1: USB disconnect, device number 1
[   12.756190] musb-hdrc musb-hdrc.1.auto: USB bus 1 deregistered
[   12.764696] reboot: System halted
```
However, with `nerves_init_gadget`, your terminal is over the USB port and you probably don't have any other terminal options. This makes this bug really hard to debug. 

Two things would be nice: 1. a nicer error message when the specified application isn't found, and 2. no crash. The latter would allow someone to connect over the USB serial port to see what happened and why the main application wasn't started. Since many (most?) people using USB gadget mode won't have an alternative console, this is probably the only way to debug.

**Comment by mobileoverlord** [comment]
Fixed in master. Thanks
